# Generated by Django 6.0.7 on 2026-08-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Department name.", max_length=150),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique department code within an institution.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional department description."
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution to which this department belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="academics.institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution", "name"),
                        name="unique_department_name_per_institution",
                    ),
                    models.UniqueConstraint(
                        fields=("institution", "code"),
                        name="unique_department_code_per_institution",
                    ),
                ],
            },
        ),
    ]
