# Generated by Django 6.0.7 on 2026-08-05 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Course name.", max_length=150)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique course code within a department.",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Course duration in years."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional course description."
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department offering this course.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="academics.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department", "name"),
                        name="unique_course_name_per_department",
                    ),
                    models.UniqueConstraint(
                        fields=("department", "code"),
                        name="unique_course_code_per_department",
                    ),
                ],
            },
        ),
    ]
