# Generated by Django 6.0.7 on 2026-08-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester_number",
                    models.PositiveSmallIntegerField(
                        help_text="Semester number (e.g. 1, 2, 3...)."
                    ),
                ),
                ("name", models.CharField(help_text="Semester name.", max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course to which this semester belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "ordering": ["course", "semester_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "semester_number"),
                        name="unique_semester_per_course",
                    )
                ],
            },
        ),
    ]
