# Generated by Django 6.0.7 on 2026-08-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record is active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(help_text="Subject code.", max_length=20)),
                ("name", models.CharField(help_text="Subject name.", max_length=200)),
                (
                    "credits",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Academic credits assigned to this subject.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional subject description."
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Semester to which this subject belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("semester", "code"),
                        name="unique_subject_code_per_semester",
                    ),
                    models.UniqueConstraint(
                        fields=("semester", "name"),
                        name="unique_subject_name_per_semester",
                    ),
                ],
            },
        ),
    ]
